### ISSUE TITLE
Fix references to `dbt-*-release-test`

### ISSUE THREAD

**Issue by emmyoop** [dbt-labs/dbt-release#53]
Release is currently broken for `dbt-spark` due to references to `dbt-spark-release-test` instead of `dbt-spark`.  Extra dependencies are therefore not installed for spark, as exxpected.

There are three references to spark in `release-prep.yml` and one in `build.yml`.   There was one reference to core in `release-prep.yml`.

As part of resolution, search other workflows to ensure this is resolved everywhere.

**Comment by emmyoop** [comment]
Also need to update [this](https://github.com/dbt-labs/dbt-release/blob/4497c9ac93395226f541d1887f308b4a10edb14f/.github/workflows/release-prep.yml#L474-L476) line to point to `dbt-core`

**Comment by alexander-smolyakov** [comment]
PR with fix #55
