### ISSUE TITLE
Remove white space after version bump

### ISSUE THREAD

**Issue by emmyoop** [dbt-labs/dbt-release#54]
The version bump is leaving white space behind.  To resolve this we need to reorg the 

[This section](https://github.com/dbt-labs/dbt-release/blob/4497c9ac93395226f541d1887f308b4a10edb14f/.github/workflows/release-prep.yml#L318-L330) needs to move to after the version bump is completed and before the changes are committed.

**Comment by alexander-smolyakov** [comment]
PR with fix #56
